services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET:-jwt-secret-key}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET:-refresh-token-secret-key}
      - WEBHOOK_URL=${WEBHOOK_URL:-https://example.com/webhook/ip-change}
      - CONFIG_PATH=/app/configs/values_local_docker.yaml
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - internal
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - internal

volumes:
  postgres_data:
    driver: local

networks:
  internal:
    driver: bridge